### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by vbusnita** [spark/spark-dev-cloud-functions#2]
[Enter steps to reproduce below:]

I modified the value of a variable. and attempted to recompile the code. The modification was minor. No reason for a compiler error. Problem appeared after I upgraded the Atom particle-dev pkg.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [particle-dev-cloud-functions](https://github.com/spark/particle-dev-cloud-functions) package, v0.0.9
### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/decorators/unhandledRejection.js:80

TypeError: Cannot read property 'toString' of undefined
  at Object.parseString (/Users/Alex/.atom/packages/spark-dev/node_modules/gcc-output-parser/lib/main.js:6:18)
  at /Users/Alex/.atom/packages/spark-dev/lib/spark-dev.coffee:584:30
  at tryCatchReject (/Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/Users/Alex/.atom/packages/particle-dev-cloud-functions/node_modules/when/lib/Scheduler.js:27:9)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```
### Commands

```
     -0:48.3.0 spark-dev:update-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:48.3.0 spark-dev:append-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:48.1.0 spark-dev:update-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:48.1.0 spark-dev:append-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:48.1.0 spark-dev:update-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:48.1.0 spark-dev:append-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:22.1.0 spark-dev:select-device (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:20.6.0 spark-dev:update-core-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:20.6.0 spark-dev:update-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:20.6.0 spark-dev:append-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:20.4.0 spark-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:19.3.0 spark-dev:compile-cloud (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:19.3.0 spark-dev:update-compile-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.8
browser-plus, v0.0.35
console-panel, v0.2.0
flex-tool-bar, v0.5.0
language-particle, v0.3.4
particle-dev-cloud-functions, v0.0.9
particle-dev-cloud-variables, v0.0.8
particle-dev-exception-reporting, v0.36.1
particle-dev-release-notes, v0.53.2
spark-dev, v0.0.30
terminal-plus, v0.8.2
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by suda** [comment]
@vbusnita thx for report. This seems to be bug [spark-dev](https://github.com/spark/particle-dev-cloud-functions/issues/2) caused by compile server outage. I added thicket for it here: https://github.com/spark/spark-dev/issues/123
