### ISSUE TITLE
Uncaught TypeError: Cannot read property 'SettingsHelper' of null

### ISSUE THREAD

**Issue by MustafaAdam** [spark/spark-dev-cloud-functions#3]
[Enter steps to reproduce below:]
1. command pallette
2. Particle Dev: Append Menu (Or any other Particle Dev command)

**Atom Version**: 1.7.4
**System**: elementary OS
**Thrown From**: [particle-dev-cloud-functions](https://github.com/spark/particle-dev-cloud-functions) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'SettingsHelper' of null

```
At /home/mustafa/.atom/packages/particle-dev-cloud-functions/lib/cloud-functions.coffee:26

TypeError: Cannot read property 'SettingsHelper' of null
    at atom-workspace._this.disposables.add.atom.commands.add.particle-dev:append-menu (/home/mustafa/.atom/packages/particle-dev-cloud-functions/lib/cloud-functions.coffee:26:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -5:43.7.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-gruvbox-syntax.theme-atom-dark-ui)
  2x -0:22.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-gruvbox-syntax.theme-atom-dark-ui)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-gruvbox-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-java",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-gfm",
      "language-mustache",
      "emmet-simplified",
      "linter-js-standard",
      "python-jedi",
      "platformio-ide-terminal",
      "atom-jinja2"
    ],
    "themes": [
      "atom-dark-ui",
      "gruvbox-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.26
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-clang, v0.9.3
autocomplete-python, v1.7.3
browser-plus, v0.0.60
build, v0.64.0
busy, v0.5.0
emmet, v2.4.3
file-icons, v1.7.13
gruvbox-syntax, v2.4.1
highlight-selected, v0.11.2
language-arduino, v0.4.1
language-babel, v2.25.1
language-ini, v1.16.0
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-gcc, v0.6.14
node-debugger, v1.7.0
particle-dev, v0.1.1
particle-dev-cloud-functions, v0.1.0
particle-dev-cloud-variables, v0.1.0
particle-dev-complete, v1.0.0
particle-dev-profiles, v0.1.1
platformio-ide, v1.2.2
platformio-ide-terminal, v2.0.10
python-autopep8, v0.1.3
python-snippets, v1.9.0
python-tools, v0.6.7
script-runner, v1.8.4
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by suda** [comment]
Thanks for reporting this Mustafa. Will look into it!

**Comment by suda** [comment]
@MustafaAdam is this still happening with particle-dev-cloud-functions@0.1.2 we released recently? BTW `Particle Dev: Append Menu` shouldn't be called from the palette (we'll hide this command).
